version: "3"

services:
  woofs_db:
    image: postgres
    container_name: woofs_db
    restart: on-failure
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=woofs
      - POSTGRES_PASSWORD=woofs
      - POSTGRES_DB=woofsdb
    volumes:
      - pgdata:/data/postgres

  woofs_app:
    build: .
    container_name: woofs_app
    restart: on-failure
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - woofs_db
    depends_on:
      - woofs_db

volumes:
  pgdata:
    driver: local
